# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = "v1.9.8"
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~> 4.1.0"
    }
    random = {
      source = "hashicorp/random"
      version = "~> 3.6.2"
    }
  }
}
