name: Generate terraform docs
run-name: CI run by ${{ github.actor }}
on:
  pull_request:
    branches:
      # ! ブランチ戦略に従って変更する必要あり(リストに追加したブランチに対しての操作がトリガーとなる)
      - main
      - develop
      - feature/*
      - renovate/*
    types:
      - opened
      - synchronize
    paths:
      # ! Terraformのディレクトリ構成に従って変更する必要あり
      - terraform/**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: terraform
          output-file: README.md
          output-method: inject
          git-push: "true"
          recursive: true
          recursive-path: .
# permissions:
#   id-token: write
#   contents: read
#   pull-requests: write
